### ISSUE TITLE
Is babel-loader now required?

### ISSUE THREAD

**Issue by binyamin** [kaicataldo/eleventy-plugin-react#24]
npm and yarn seem to think I need to install `babel-loader`, which I don't remember needing before. Also, the readme doesn't mention it. But it _is_ listed in the peerDependencies. Just an FYI.

**Comment by kaicataldo** [comment]
`babel-loader` is definitely a requirement! Missing it in the readme was an oversight - sorry about that!

**Comment by kaicataldo** [comment]
Updated the readme. Thanks for catching that.

**Comment by kaicataldo** [comment]
For reference, it became a requirement when implementing [this feature]https://github.com/kaicataldo/eleventy-plugin-react/commit/51282590917081962d8b4a3ef5eb1e2d412a2f30#diff-313d0f90cb373ee6b9e0c988e71aaca3a3960bad3d108b163fdb4ad80b2e6894) (though I mistakenly added it as a dep instead of a peer dep - fixed in a later commit 😓 )

**Comment by binyamin** [comment]
@kaicataldo Cheers!
